### ISSUE TITLE
about optimal hyperparameters

### ISSUE THREAD

**Issue by haopetter** [AutoML-Research/KGTuner#2]
作者大大，您好，请问有直接用最优超参数训练基础模型的版本吗，我在这篇现有代码的版本上将有关参数搜索的部分删掉了，直接用最优超参训练，但是结果不太对，感谢！！

**Comment by AndrewZhou924** [comment]
Hi, you can provide more information for debugging :)
E.g., how did you modify the code, and which model and dataset are you working on?
